In [27]:
import numpy as np

#constants
c1 = -0.138754
c2 = -0.152989
c3 = +0.164190
c4 = +0.144579
c5 = +0.111373
c6 = +0.146726
c7 = +0.169348
c8 = -0.035353
c9 = +0.035353

# Pauli X matrix
X = np.array([[0, 1], [1, 0]])
# Pauli Y matrix
Y = np.array([[0, -1j], [1j, 0]])
# Pauli Z matrix
Z = np.array([[1, 0], [0, -1]])
# Identity matrix
I = np.array([[1, 0],[0, 1]])

a = np.kron(I,I)
a1 = np.kron(a,I)
a2 = np.kron(a1,I)

b = np.kron(I,I)
b1 = np.kron(b,Z)
b2 = np.kron(b1,I)

u = np.kron(I,I)
u1 = np.kron(u,I)
u2 = np.kron(u1,Z)

t = np.kron(Z,I)
t1 = np.kron(t,I)
t2 = np.kron(t1,I)

s = np.kron(I,Z)
s1 = np.kron(s,I)
s2 = np.kron(s1,I)

k = np.kron(I,I)
k1 = np.kron(k,Z)
k2 = np.kron(k1,Z)

k3 = np.kron(I,Z)
k4 = np.kron(k3,I)
k5 = np.kron(k4,Z)

k6 = np.kron(Z,I)
k7 = np.kron(k6,Z)
k8 = np.kron(k7,I)

k9 = np.kron(I,Z)
k10 = np.kron(k9,Z)
k11 = np.kron(k10,I)

w = np.kron(Z,I)
w1 = np.kron(w,I)
w2 = np.kron (w1,Z)

w3 = np.kron(Z,Z)
w4 = np.kron(w3,I)
w5 = np.kron(w4,I)

w6 = np.kron(X,X)
w7 = np.kron(w6,Y)
w8 = np.kron(w7,Y)

r = np.kron(Y,Y)
r1 = np.kron(r,X)
r2 = np.kron(r1,X)

r3 = np.kron(X,Y)
r4 = np.kron(r3,Y)
r5 = np.kron(r4,X)

o = np.kron(Y,X)
o1 = np.kron(o,X)
o2 = np.kron(o1,Y)

#The Hydrogen matrix
Hydro = c1*a2 + c2*b2 + c2*u2 + c3*t2 + c3*s2 + c4*k2 + c5*k5 + c5*k8 + c6*k11 + c6*w2
+c7*w5 + c8*w8 + c8*r2 + c9*r5 + c9*o2

print(Hydro)


[[ 0.544425  0.        0.        0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.
   0.        0.      ]
 [ 0.        0.045047  0.        0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.
   0.        0.      ]
 [ 0.        0.        0.045047  0.        0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.
   0.        0.      ]
 [ 0.        0.        0.        0.123985  0.        0.        0.
   0.        0.        0.        0.        0.        0.        0.
   0.        0.      ]
 [ 0.        0.        0.        0.       -0.300153  0.        0.
   0.        0.        0.        0.        0.        0.        0.
   0.        0.      ]
 [ 0.        0.        0.        0.        0.       -0.354039  0.
   0.        0.        0.        0.        0.        0.        0.
   0.        0.      ]
 [ 0.        0.        0.        0.        0.        0.       -0.21262

In [28]:

def ground_state(density_matrix):
  """
  Finds the ground state energy (smallest eigenvalue), 
  eigenvectors, and eigenvalues of a density matrix.

  Args:
      density_matrix: A square numpy array representing the density matrix.

  Returns:
      A tuple containing the ground state energy (float), 
      eigenvectors (numpy array), and eigenvalues (numpy array).
  """
  eigenvalues, eigenvectors = np.linalg.eigh(density_matrix)
  ground_state_energy = np.min(eigenvalues)
  return ground_state_energy, eigenvectors, eigenvalues

# Example usage
density_matrix = np.array(Hydro)
ground_state_energy, eigenvectors, eigenvalues = ground_state(density_matrix)

print("Ground state energy:", ground_state_energy)
print("Eigenvectors:\n", eigenvectors)
print("Eigenvalues:\n", eigenvalues)


Ground state energy: -1.144731
Eigenvectors:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Eigenvalues:
 [-1.144731 -0.611713 -0.611713 -0.354039 -0.354039 -0.300153 -0.300153
 -0.212627 -0.212627  0.045047  0.045047  0.123985  