In [10]:
# Pauli X gate
X = np.array([[0, 1], [1, 0]])
# Pauli Y gate
Y = np.array([[0, -1j], [1j, 0]])
# Pauli Z gate
Z = np.array([[1, 0], [0, -1]])

# Identity gate
I = np.array([[1, 0], [0, 1]])
a = np.kron(Z,I)
b = np.kron(a,I)

print(b)

[[ 1  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0 -1]]
